name: expense
version: '3.8'
networks:
  default: 
    name: expense
volumes:
  mysql: # docker volume crete mysql
services:
  mysql: 
    image: mysql:v1.0
    container_name: mysql  # --name mysql
    volumes:
     - mysql:/var/lib/mysql
  backend:
    image: backend:v1.0
    container_name: backend 
    depends_on: 
      - mysql
    command: sh -c "sleep 20 && node /opt/backend/index.js"
  frontend:
    image: frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"