name: expense
networks:
  default:
    name: expense
volumes:
  mysql: # docker volume crete mysql
    #external: true # if true, you need to create manually
       # docker volume create myqsl
services:
  mysql: 
    #image: mysql:v1.0
    image: dev0pslearning2025/mysql:v1.0
    container_name: mysql  # --name mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=Expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
  backend:
    #image: backend:v1.0
    image: dev0pslearning2025/backend:v1.0
    container_name: backend 
    depends_on: 
      - mysql
    command: sh -c "sleep 20 && node /opt/backend/index.js"
  frontend:
    #image: frontend:v1.0
    image: dev0pslearning2025/frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"